### ISSUE TITLE
Unit tests breaking on master branch

### ISSUE THREAD

**Issue by davidcmoulton** [stencila/thema#161]
Steps to reproduce:
1. `git clone git@github.com:stencila/thema.git && cd thema`
1. `npm install && npm run bootstrap`
1.  `npm run test:unit`

```
david:~/work/elife/temp/thema/thema (master)$ npm run test:unit

> @stencila/thema@2.7.2 test:unit /Users/david/work/elife/temp/thema/thema
> jest

(node:8299) ExperimentalWarning: The fs.promises API is experimental
(node:8297) ExperimentalWarning: The fs.promises API is experimental
(node:8301) ExperimentalWarning: The fs.promises API is experimental
(node:8298) ExperimentalWarning: The fs.promises API is experimental
(node:8302) ExperimentalWarning: The fs.promises API is experimental
(node:8300) ExperimentalWarning: The fs.promises API is experimental
ts-jest[versions] (WARN) Version 26.0.1 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=25.0.0 <26.0.0). Please do not report issues in ts-jest if you are using unsupported versions.
ts-jest[versions] (WARN) Version 26.0.1 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=25.0.0 <26.0.0). Please do not report issues in ts-jest if you are using unsupported versions.
ts-jest[versions] (WARN) Version 26.0.1 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=25.0.0 <26.0.0). Please do not report issues in ts-jest if you are using unsupported versions.
ts-jest[versions] (WARN) Version 26.0.1 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=25.0.0 <26.0.0). Please do not report issues in ts-jest if you are using unsupported versions.
ts-jest[versions] (WARN) Version 26.0.1 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=25.0.0 <26.0.0). Please do not report issues in ts-jest if you are using unsupported versions.
ts-jest[versions] (WARN) Version 26.0.1 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=25.0.0 <26.0.0). Please do not report issues in ts-jest if you are using unsupported versions.
 FAIL  src/extensions/cite-apa/index.test.ts
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/en/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.

    ReferenceError: document is not defined

      1 | import { select, text, whenReady } from '../../util'
      2 |
    > 3 | const body = document.body
        |              ^
      4 |
      5 | test('DOM manipulations', async () => {
      6 |   body.innerHTML = `

      at Object.<anonymous> (src/extensions/cite-apa/index.test.ts:3:14)

 FAIL  src/browser/index.test.ts
  ● Test suite failed to run

    ReferenceError: describe is not defined

      2 | import { isTheme } from '.'
      3 |
    > 4 | describe('Check if `theme` is a Thema theme', () => {
        | ^
      5 |   test.each(Object.keys(themes))('Thema themes - %s', (themeKey) => {
      6 |     expect(isTheme(themeKey)).toBe(true)
      7 |   })

      at Object.<anonymous> (src/browser/index.test.ts:4:1)

 FAIL  src/extensions/code/index.test.ts
  ● Test suite failed to run

    ReferenceError: test is not defined

      1 | import { attr, first, whenReady } from '../../util/index'
      2 |
    > 3 | test('Syntax highlighting of CodeBlocks', async () => {
        | ^
      4 |   document.body.innerHTML = `
      5 |     <pre itemscope="" itemtype="http://schema.stenci.la/CodeBlock">
      6 |       <code></code>

      at Object.<anonymous> (src/extensions/code/index.test.ts:3:1)

 FAIL  src/themes/elife/test/dataProvider.test.ts
  ● Test suite failed to run

    ReferenceError: describe is not defined

       6 | }
       7 |
    >  8 | describe('data Provider ', () => {
         | ^
       9 |   describe('successfully querying a valid article id', () => {
      10 |     it('does not throw', async () => {
      11 |       const fetchMock = (): Promise<Response> =>

      at Object.<anonymous> (src/themes/elife/test/dataProvider.test.ts:8:1)

 FAIL  src/util/index.test.ts
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/en/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.

    ReferenceError: document is not defined

      17 | } from '.'
      18 |
    > 19 | const body = document.body
         |              ^
      20 |
      21 | describe('ready', () => {
      22 |   it('runs the functions, in order, when the DOM is ready', (done) => {

      at Object.<anonymous> (src/util/index.test.ts:19:14)

 FAIL  test/selectors.test.ts
  ● Test suite failed to run

    ReferenceError: describe is not defined

       8 | import { promisify } from 'util'
       9 |
    > 10 | describe('semantic selectors are valid', () => {
         | ^
      11 |   const srcDir = path.join(__dirname, '..', 'src')
      12 |
      13 |   const selectors = fs

      at Object.<anonymous> (test/selectors.test.ts:10:1)

Test Suites: 6 failed, 6 total
Tests:       0 total
Snapshots:   0 total
Time:        3.12 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @stencila/thema@2.7.2 test:unit: `jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @stencila/thema@2.7.2 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/david/.npm/_logs/2020-05-11T10_56_59_963Z-debug.log
```

**Comment by alex-ketch** [comment]
@davidcmoulton Unfortunately I wasn't able to reproduce this bug :/
I tried on a fresh clone of the repository using Node `v10.16.3`, `v12.13.0`, and `v13.13.0`.
In case you haven't tried it on a fresh install, would you mind clearing out your `node_modules` and running `npm install` please?

Either way, I'm going to verify the dependency changes on https://github.com/stencila/thema/pull/151, and merge it into `master`. Hopefully that should address any issues you might be facing.

**Comment by davidcmoulton** [comment]
@alex-ketch thanks for looking into this. I checked and I was on a slightly older version of node (10.12). I've now switched to node `10.16.3` (current LTS) and that seems to have fixed the problem 😅 Wondering if it might be worth adding an `engines` field to the `package.json`?
